services:
    nextjs:
        container_name: next
        build: ./next-js
        network_mode: "host"
        env_file:
            - ./next-js/.env
        depends_on:
            - express

    express:
        container_name: express
        build: ./express
        restart: "always"
        network_mode: "host"
        env_file:
            - ./express/.env

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        restart: "always"
        network_mode: "host"
        volumes:
            - myapp:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

    nodemailer:
        container_name: nodemailer
        build: ./nodemailer
        network_mode: "host"
        restart: "unless-stopped"
        env_file:
            - ./nodemailer/.env
        depends_on:
            - rabbitmq

    mysql-workbench:
        image: lscr.io/linuxserver/mysql-workbench:latest
        container_name: mysql-workbench
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - myapp:/config
        ports:
            - 3000:3000
            - 3001:3001
        cap_add:
            - IPC_LOCK
        restart: unless-stopped

volumes:
    myapp:
