services:
    nextjs:
        container_name: nextjs-app
        build: ./express
        network_mode: "host"
        env_file:
            - ./express/.env

    express:
        container_name: express-app
        build: ./express
        restart: "always"
        network_mode: "host"
        env_file:
            - ./backend/.env
