services:
    nextjs:
        container_name: nextjs-app
        build: ./frontend
        network_mode: "host"
        env_file:
            - ./frontend/.env

    express:
        container_name: express-app
        build: ./backend
        restart: "always"
        network_mode: "host"
        env_file:
            - ./backend/.env
