services:
    nextjs:
        container_name: next
        build: ./next-js
        network_mode: "host"
        env_file:
            - .env

    express:
        container_name: express
        build: ./express
        restart: "always"
        network_mode: "host"
        env_file:
            - .env
