# Specify the node base image
FROM node:latest

# Create app directory in the container
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Your app binds to port 4000 so you'll use the EXPOSE instruction to have it mapped
EXPOSE 4000

# Define the command to run your app
CMD ["npm", "run", "start"]
