name: Next.js + Express CI

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:

concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
