name: Deploy Docker Compose Dev Environment in Dev

on:
  push:
    branches:
      - dev # Change this to your preferred branch

jobs:
  deploy:
    runs-on: ['self-hosted', 'test']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Stop existing Docker Compose setup
      working-directory: /home/africarice/africarice-hr-test
      run: |
        docker compose -f docker-compose.dev.yml down

    - name: Pull latest commit
      working-directory: /home/africarice/africarice-hr-test
      run: |
        git fetch
        git checkout dev    # Ensure you are on the correct branch
        git pull origin dev # Pull the latest commits

    - name: Rebuild and restart Docker Compose
      working-directory: /home/africarice/africarice-hr-test
      run: |
        docker compose up -f docker-compose.dev.yml --build -d --remove-orphans
